<?php

/**
 * @file
 * Provides entity types for Course and Programmes.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function occapi_entities_theme() {
  return [
    'course' => [
      'render element' => 'elements',
    ],
    'programme' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for course templates.
 *
 * Default template: course.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the course information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_course(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for programme templates.
 *
 * Default template: programme.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the programme information and
 *     any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_programme(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
